// <auto-generated />
using System;
using Consolidation.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consolidation.API.Migrations.Sales
{
    [DbContext(typeof(SalesItemContext))]
    [Migration("20260406150004_InitialSqlServerSales")]
    partial class InitialSqlServerSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consolidation.API.Model.Sales.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<int>("MinorUnit")
                        .HasColumnType("int")
                        .HasColumnName("minor_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int?>("NumericCode")
                        .HasColumnType("int")
                        .HasColumnName("numeric_code");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("symbol");

                    b.HasKey("Code")
                        .HasName("pk_currency");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_currency_code");

                    b.ToTable("currency", "sales", t =>
                        {
                            t.HasComment("master currency list with ISO codes, symbols, and minor-unit precision");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("effective_utc");

                    b.Property<string>("FromCurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("from_currency_code");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("rate");

                    b.Property<string>("ToCurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("to_currency_code");

                    b.HasKey("Id")
                        .HasName("pk_exchange_rate");

                    b.HasIndex("ToCurrencyCode")
                        .HasDatabaseName("ix_exchange_rate_to_currency_code");

                    b.HasIndex("FromCurrencyCode", "ToCurrencyCode", "EffectiveUtc")
                        .HasDatabaseName("ix_exchange_rate_from_currency_code_to_currency_code_effective_utc");

                    b.ToTable("exchange_rate", "sales", t =>
                        {
                            t.HasComment("time-based exchange rates between source and target currencies");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("int")
                        .HasColumnName("parent_menu_id");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("path");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_menu");

                    b.HasIndex("ParentMenuId")
                        .HasDatabaseName("ix_menu_parent_menu_id");

                    b.HasIndex("ModuleId", "ParentMenuId", "SortOrder")
                        .HasDatabaseName("ix_menu_module_id_parent_menu_id_sort_order");

                    b.ToTable("menu", "sales", t =>
                        {
                            t.HasComment("recursive menu tree used for role-filtered navigation in the UI control layer");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.MenuRole", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.Property<string>("RoleName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("role_name");

                    b.HasKey("MenuId", "RoleName")
                        .HasName("pk_menu_role");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("ix_menu_role_role_name");

                    b.ToTable("menu_role", "sales", t =>
                        {
                            t.HasComment("role-to-menu visibility mappings used to filter the UI menu tree");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_module");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_module_code");

                    b.ToTable("module", "sales", t =>
                        {
                            t.HasComment("ui control modules used to group ERP navigation areas");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.SalesItemItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableStock")
                        .HasColumnType("int")
                        .HasColumnName("available_stock");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("barcode");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("base_currency_code");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("base_price");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Embedding")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("embedding");

                    b.Property<int>("MaxStockThreshold")
                        .HasColumnType("int")
                        .HasColumnName("max_stock_threshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<bool>("OnReorder")
                        .HasColumnType("bit")
                        .HasColumnName("on_reorder");

                    b.Property<string>("PictureFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("picture_file_name");

                    b.Property<int>("RestockThreshold")
                        .HasColumnType("int")
                        .HasColumnName("restock_threshold");

                    b.Property<int>("SalesItemBrandId")
                        .HasColumnType("int")
                        .HasColumnName("sales_item_brand_id");

                    b.Property<int>("SalesItemTypeId")
                        .HasColumnType("int")
                        .HasColumnName("sales_item_type_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_salesitem");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("ix_salesitem_barcode");

                    b.HasIndex("BaseCurrencyCode")
                        .HasDatabaseName("ix_salesitem_base_currency_code");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_salesitem_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_salesitem_name");

                    b.HasIndex("SalesItemBrandId")
                        .HasDatabaseName("ix_salesitem_sales_item_brand_id");

                    b.HasIndex("SalesItemTypeId")
                        .HasDatabaseName("ix_salesitem_sales_item_type_id");

                    b.ToTable("salesitem", "sales", t =>
                        {
                            t.HasComment("product catalog items with pricing, stock thresholds, and serialized embedding payload");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.SalesItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_salesitem_type");

                    b.ToTable("salesitem_type", "sales", t =>
                        {
                            t.HasComment("type or category reference data for catalog items");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.SalesitemBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("brand");

                    b.HasKey("Id")
                        .HasName("pk_salesitem_brand");

                    b.ToTable("salesitem_brand", "sales", t =>
                        {
                            t.HasComment("brand reference data for catalog items");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.SalesitemDimension", b =>
                {
                    b.Property<int>("SalesItemId")
                        .HasColumnType("int")
                        .HasColumnName("sales_item_id");

                    b.Property<int?>("DimensionUnitId")
                        .HasColumnType("int")
                        .HasColumnName("dimension_unit_id");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("height");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("length");

                    b.Property<int?>("QuantityUnitId")
                        .HasColumnType("int")
                        .HasColumnName("quantity_unit_id");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("weight");

                    b.Property<int?>("WeightUnitId")
                        .HasColumnType("int")
                        .HasColumnName("weight_unit_id");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("width");

                    b.HasKey("SalesItemId")
                        .HasName("pk_salesitem_dimension");

                    b.HasIndex("DimensionUnitId")
                        .HasDatabaseName("ix_salesitem_dimension_dimension_unit_id");

                    b.HasIndex("QuantityUnitId")
                        .HasDatabaseName("ix_salesitem_dimension_quantity_unit_id");

                    b.HasIndex("WeightUnitId")
                        .HasDatabaseName("ix_salesitem_dimension_weight_unit_id");

                    b.ToTable("salesitem_dimension", "sales", t =>
                        {
                            t.HasComment("physical dimensions, weight, and units for a catalog item");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.SalesitemPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("price");

                    b.Property<int>("SalesItemId")
                        .HasColumnType("int")
                        .HasColumnName("sales_item_id");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_salesitem_price");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_salesitem_price_currency_code");

                    b.HasIndex("SalesItemId", "CurrencyCode")
                        .IsUnique()
                        .HasDatabaseName("ix_salesitem_price_sales_item_id_currency_code");

                    b.ToTable("salesitem_price", "sales", t =>
                        {
                            t.HasComment("currency-specific price entries with optional effective date ranges");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("config_value");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("pk_system_config");

                    b.HasIndex("ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("ix_system_config_config_key");

                    b.ToTable("system_config", "sales", t =>
                        {
                            t.HasComment("key-value configuration entries used by the sales catalog subsystem");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.UnitMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("measurement_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_unit_measurement");

                    b.HasIndex("MeasurementType")
                        .HasDatabaseName("ix_unit_measurement_measurement_type");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_measurement_symbol");

                    b.ToTable("unit_measurement", "sales", t =>
                        {
                            t.HasComment("reference units for length, weight, and quantity measurements");
                        });
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.ExchangeRate", b =>
                {
                    b.HasOne("Consolidation.API.Model.Sales.Currency", "FromCurrency")
                        .WithMany()
                        .HasForeignKey("FromCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exchange_rate_currency_from_currency_code");

                    b.HasOne("Consolidation.API.Model.Sales.Currency", "ToCurrency")
                        .WithMany()
                        .HasForeignKey("ToCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exchange_rate_currency_to_currency_code");

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.Menu", b =>
                {
                    b.HasOne("Consolidation.API.Model.Sales.Module", "Module")
                        .WithMany("Menus")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_module_module_id");

                    b.HasOne("Consolidation.API.Model.Sales.Menu", "ParentMenu")
                        .WithMany("Children")
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_menu_menu_parent_menu_id");

                    b.Navigation("Module");

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.MenuRole", b =>
                {
                    b.HasOne("Consolidation.API.Model.Sales.Menu", "Menu")
                        .WithMany("MenuRoles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_role_menu_menu_id");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.SalesItemItem", b =>
                {
                    b.HasOne("Consolidation.API.Model.Sales.Currency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_salesitem_currency_base_currency_code");

                    b.HasOne("Consolidation.API.Model.Sales.SalesitemBrand", "SalesItemBrand")
                        .WithMany()
                        .HasForeignKey("SalesItemBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_salesitem_salesitem_brand_sales_item_brand_id");

                    b.HasOne("Consolidation.API.Model.Sales.SalesItemType", "SalesItemType")
                        .WithMany()
                        .HasForeignKey("SalesItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_salesitem_salesitem_type_sales_item_type_id");

                    b.Navigation("BaseCurrency");

                    b.Navigation("SalesItemBrand");

                    b.Navigation("SalesItemType");
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.SalesitemDimension", b =>
                {
                    b.HasOne("Consolidation.API.Model.Sales.UnitMeasurement", "DimensionUnit")
                        .WithMany()
                        .HasForeignKey("DimensionUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_salesitem_dimension_unit_measurement_dimension_unit_id");

                    b.HasOne("Consolidation.API.Model.Sales.UnitMeasurement", "QuantityUnit")
                        .WithMany()
                        .HasForeignKey("QuantityUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_salesitem_dimension_unit_measurement_quantity_unit_id");

                    b.HasOne("Consolidation.API.Model.Sales.SalesItemItem", "SalesItem")
                        .WithOne("Dimension")
                        .HasForeignKey("Consolidation.API.Model.Sales.SalesitemDimension", "SalesItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_salesitem_dimension_salesitem_sales_item_id");

                    b.HasOne("Consolidation.API.Model.Sales.UnitMeasurement", "WeightUnit")
                        .WithMany()
                        .HasForeignKey("WeightUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_salesitem_dimension_unit_measurement_weight_unit_id");

                    b.Navigation("DimensionUnit");

                    b.Navigation("QuantityUnit");

                    b.Navigation("SalesItem");

                    b.Navigation("WeightUnit");
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.SalesitemPrice", b =>
                {
                    b.HasOne("Consolidation.API.Model.Sales.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_salesitem_price_currency_currency_code");

                    b.HasOne("Consolidation.API.Model.Sales.SalesItemItem", "SalesItem")
                        .WithMany("Prices")
                        .HasForeignKey("SalesItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_salesitem_price_salesitem_sales_item_id");

                    b.Navigation("Currency");

                    b.Navigation("SalesItem");
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MenuRoles");
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.Module", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("Consolidation.API.Model.Sales.SalesItemItem", b =>
                {
                    b.Navigation("Dimension");

                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
